# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master
      - development
  paths:
    exclude:
      - '*.yml'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'testbenchnet_dockerhub'
  imageRepository: 'testbenchnet/basicdocker'


stages:
- stage: Build

  jobs:
  - job: Buildandpush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Visual Studio Professional with MSDN (acda883c-5d94-441c-b0a6-114732847932)'
        appName: 'canyonblack-basicdocker-dev-as'
        containers: 'https://hub.docker.com/repository/docker/testbenchnet/basicdocker$(tag)'
        #containerCommand: 'docker run basicdocker -p 80:80'
