# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master
      - development
  paths:
    exclude:
      - '*.yml'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'testbenchnet_dockerhub'
  imageRepository: 'testbenchnet/basicdocker'
  azureSubscriptionName: 'Visual Studio Professional with MSDN (acda883c-5d94-441c-b0a6-114732847932)'
  containerName: 'testbenchnet/basicdocker:$(tag)'
  appServiceName: 'canyonblack-basicdocker-dev-as'

stages:
- stage: Build

  jobs:
  - job: Buildandpush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: '$(azureSubscriptionName)'
        appName: '$(appServiceName)'
        containers: '$(containerName)'
        //containerCommand: -p 443:443 -p 80:80
        
